---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakebook-auth-api
  labels:
    app: fakebook-auth
    role: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakebook-auth
      role: api
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fakebook-auth
        role: api
    spec:
      containers:
      - name: api
        image: fakebook.azurecr.io/fakebookauth:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__FakebookAuth
          value: 'Host=fakebook-auth-db;Database=postgres;Username=postgres;Password=Pass@word'
        envFrom:
        - secretRef:
            name: fakebook-auth-config
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakebook-auth-db
  labels:
    app: fakebook-auth
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakebook-auth
      role: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fakebook-auth
        role: db
    spec:
      containers:
      - name: db
        image: fakebook.azurecr.io/fakebookauth-db:latest
        env:
        - name: POSTGRES_PASSWORD
          value: Pass@word
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume
          subPath: data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: fakebook-auth
